[package]
name = "domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulid = { version = "1" }
anyhow = { version = "1" }
chrono = { version = "0.4" }
async-trait = { version = "0.1"}
